# Site settings
title: Johannes Dwi Cahyo
description: 'Rails, Ionic Dev & Culinary Entrepeneur'
url: 'http://johannesdwicahyo.id'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Johannes Dwi Cahyo'
  email: johannesdwicahyo@gmail.com
  twitter_username: jdwicahyo
  facebook_username: johannesdwicahyo
  github_username:  c4hj0
  linkedin_username:  johannesdwicahyo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
